language:
  - c++

os:
  - linux

compiler:
  - gcc
  - g++
  - clang

before_install:
  - test -n $CC && unset CC

install:
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
  - sudo apt-get install libopencv-*

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make -j4

  - mpirun -np 4 ./modules/test_task/test_task
  - mpirun -np 4 ./modules/task_1/vikhrev_array_sum/vikhrev_array_sum 10 10
